# Generated by Django 6.0.4 on 2026-10-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('create_chama', 'Create chama'), ('view_chama_details', 'View chama details'), ('update_chama_info', 'Update chama info'), ('configure_chama_settings', 'Configure chama settings'), ('add_members', 'Add members'), ('view_members', 'View members'), ('update_member_information', 'Update member information'), ('remove_member', 'Remove member'), ('view_reports', 'View reports'), ('view_audits', 'View audits')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.CharField(max_length=254)),
                ('action', models.CharField(max_length=100)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
