# Generated by Django 6.0.4 on 2026-10-05 18:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamaMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=16)),
                ('national_id', models.CharField(blank=True, max_length=8)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('joined_on', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chama.chama')),
            ],
            options={
                'ordering': ['full_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), models.Q(('national_id', ''), _negated=True)), fields=('chama', 'national_id'), name='uniq_active_member_national_id')],
            },
        ),
    ]
