# Generated by Django 6.0.4 on 2026-10-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamamember',
            name='country',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='county',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='employer_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='employer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='employment_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='estate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='kin_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='kin_full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='kin_phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='kin_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='nationality',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='physical_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='postal_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='source_of_income',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chamamember',
            name='town',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
