# Generated by Django 6.0.4 on 2026-10-05 18:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chama', '0001_initial'),
        ('member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('chairperson', 'Chairperson'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer')], max_length=12)),
                ('appointed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('appointed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='chama.chama')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='member.chamamember')),
            ],
            options={
                'ordering': ['position', '-appointed_on', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_on__isnull', True)), fields=('chama', 'position'), name='uniq_current_office_holder'), models.UniqueConstraint(condition=models.Q(('ended_on__isnull', True)), fields=('member',), name='uniq_one_current_office_per_member')],
            },
        ),
    ]
