# Generated by Django 6.0.4 on 2026-10-05 08:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('chama_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('meeting_frequency', models.CharField(max_length=255)),
                ('contribution', models.IntegerField(default=0)),
                ('share_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pool_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('loan_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='onboarding', max_length=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chamas', to='employee.employee')),
            ],
        ),
    ]
