# Generated by Django 6.0.4 on 2026-10-06 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chama',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
