# Generated by Django 6.0.4 on 2026-10-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0002_chama_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chama',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
